---
- name: "Docker setup - RedHat"
  ansible.builtin.import_tasks: docker-core-redhat.yml
  when: ansible_os_family == "RedHat"

- name: "Docker setup - Debian"
  ansible.builtin.import_tasks: docker-core-debian.yml
  when: ansible_os_family == "Debian"

- name: "Setup latest docker-compose"
  ansible.builtin.import_tasks: install-compose.yml

- name: "Start and enable docker service"
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
