---
- name: "Create project directory"
  ansible.builtin.file:
    path: "/opt/wordpress/{{ item }}"
    state: directory
  loop:
    - ""
    - wordpress
    - db

- name: "Copy Dockerfiles and docker-compose.yml"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/opt/wordpress/{{ item }}"
  loop:
    - wordpress/Dockerfile
    - db/Dockerfile
    - docker-compose.yml
